[variables]
CI = 'true'
#NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
#NPM_CONFIG_PRODUCTION = 'false'
NIXPACKS_NODE_VERSION = '20'

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
